version: '3'
services:
  bastillion:
    image: bastillion:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bastillion
    hostname: bastillion
    environment:
      JAVA_OPTS: "-Xms1024m -Xmx1024m"
      PRIVATEKEYNAME: ""     # 若要系統產生，則使用空值
      PUBLICKEYNAME: ""  # 若要系統產生，則使用空值
    ports:
      - "8443:8443"
    volumes:
      - ./data/keydb:/Bastillion-jetty/jetty/bastillion/WEB-INF/classes/keydb
      - ./data/logs:/Bastillion-jetty/jetty/logs
      - ./data/sshkey:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
