version: '3'
services:
  bastillion:
    image: r19750927/bastillion:${BASTILLION_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BASTILLION_VERSION: ${BASTILLION_VERSION}
    container_name: bastillion
    hostname: bastillion
    environment:
      JAVA_OPTS: ${JAVA_OPTS}
      PRIVATEKEYNAME: ${PRIVATEKEYNAME}
      PUBLICKEYNAME: ${PUBLICKEYNAME}
      EnableInternalAudit: ${EnableInternalAudit}
    ports: 
      - "8443:8443"
    volumes:
      - ./data/keydb:/Bastillion-jetty/jetty/bastillion/WEB-INF/classes/keydb
      - ./data/logs:/Bastillion-jetty/jetty/logs
      - ./data/keyfile:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
